#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "yuno_goti_notify"
name = "Yuno_Goti_Notify"
description.en = "A collection of Yunohost hooks to send notifications to a Gotify server"
description.fr = "Une collection de hooks Yunohost pour envoyer des notifications vers un serveur Gotify"

version = "0.1~ynh4"

maintainers = ["DeMiro5001"]

[upstream]
license = "MIT"
admindoc = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications/blob/main/README.md"
userdoc = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications/blob/main/README.md"
code = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications"

[integration]
yunohost = ">= 12.0"
helpers_version = "2.1"
architectures = "all"
multi_instance = true
ldap = false
sso = false
disk = "1M"
ram.build = "1M"
ram.runtime = "1M"

[install]
    [install.gotify]
    ask.en = "What's the url of your Gotify server ?"
    ask.fr = "Quelle est l'addresse url de votre serveur Gotify ?"
    type = "url"

    [install.apptoken]
    ask.en = "App token for app on this server"
    ask.fr = "Jeton de l'application sur ce serveur"
    type = "string"

    [install.server]
    ask.en = "Display name for this server (this will be used in the title of notifications)"
    ask.fr = "Nom d'affichage de ce serveur (ceci sera utilisé dans le titre des notifications)"
    type = "string"
    
[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/DeMiro5001/Yunohost_Gotify_Notifications/archive/refs/tags/0.1.tar.gz"
    sha256 = "50c3c8328f344a22136b06b0dc600facb124fd881d6b9b44effbd4e9eeb42a13"
    autoupdate.strategy = "latest_github_tag"
    
    [resources.system_user]

    [resources.data_dir]
