#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/tests.v1.schema.json

test_format = 1.0

[default]

    args.apptoken = "1234567890"
    args.gotify ="https://yunohost.org"
    args.server = "My yunohost home server"
