#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

gotifypath=$gotify
ynh_app_setting_set --key=gotifypath --value=$gotifypath

token=$apptoken
ynh_app_setting_set --key=token --value=$token

server_id=$(cat /etc/machine-id)
ynh_app_setting_set --key=server_id --value=$server_id

ynh_app_setting_set --key=server --value=$server

#=================================================
# SETUP HOOKS
#=================================================
ynh_script_progression "Setting up hooks..."

ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/backup"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/restore"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_install"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_remove"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_upgrade"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_cert_update"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_domain_add"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_domain_remove"

ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/backup"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/restore"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_install"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_remove"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_upgrade"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_cert_update"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_domain_add"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_domain_remove"

ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/backup"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/restore"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_app_install"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_app_remove"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_app_upgrade"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_cert_update"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_domain_add"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_domain_remove"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

# Strip https://
gotifypath=${gotifypath#*//}

ynh_config_add --template="../conf/gotify_ssh_login.sh" --destination="/etc/profile.d/gotify_ssh_login_$app.sh"

chmod 600 "/etc/profile.d/gotify_ssh_login_$app.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
