#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

hooks_dir="/etc/yunohost/hooks.d/"

#=================================================
# REMOVE SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

rm "$hooks_dir/post_domain_add/01-post_domain_add_$server_id"
rm "$hooks_dir/post_domain_remove/01-post_domain_remove_$server_id"
rm "$hooks_dir/post_cert_update/01-post_cert_update_$server_id"
rm "$hooks_dir/backup/01-backup_$server_id"
rm "$hooks_dir/restore/01-restore_$server_id"
rm "$hooks_dir/post_app_install/01-post_app_install_$server_id"
rm "$hooks_dir/post_app_remove/01-post_app_remove_$server_id"
rm "$hooks_dir/post_app_upgrade/01-post_app_upgrade_$server_id"
rm "/etc/profile.d/gotify_ssh_login_$server_id.sh"### This should be a symetric version of what happens in the install script

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
