#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

gotify=$(ynh_app_setting_get --app=$app --key=gotify)
apptoken=$(ynh_app_setting_get --app=$app --key=apptoken)
server=$(ynh_app_setting_get --app=$app --key=server)

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# SETUP HOOKS
#=================================================
ynh_script_progression "Setting up hooks..."

ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/backup"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/restore"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_install"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_remove"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_upgrade"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_cert_update"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_domain_add"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_domain_remove"

ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/backup"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/restore"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_install"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_remove"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_upgrade"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_cert_update"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_domain_add"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_domain_remove"

ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/backup"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/restore"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_app_install"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_app_remove"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_app_upgrade"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_cert_update"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_domain_add"
ynh_replace --match="__SERVER__" --replace="$server" --file="../hooks/post_domain_remove"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_config_add --template="$data_dir/etc/profile.d/gotify_ssh_login.sh" --destination="/etc/profile.d/gotify_ssh_login_$app.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
