#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source /usr/share/yunohost/helpers

gotify=$(ynh_app_setting_get --app=$app --key=gotify)
apptoken=$(ynh_app_setting_get --app=$app --key=apptoken)
server=$(ynh_app_setting_get --app=$app --key=server)

#=================================================
# RESTORE VARIOUS FILES
#=================================================

ynh_script_progression "Restoring $app's configuration files..."

ynh_config_add --template="$data_dir/etc/profile.d/gotify_ssh_login.sh" --destination="/etc/profile.d/gotify_ssh_login_$app.sh"
chmod 600 "/etc/profile.d/gotify_ssh_login_$app.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
