#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTORE THE DATA DIRECTORY
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE VARIOUS FILES
#=================================================

cd $hooks_dir
mkdir post_domain_add post_domain_remove post_cert_update backup restore post_app_install post_app_remove post_app_upgrade 2>&1

ynh_config_add --template="$data_dir/post_domain_add/01-post_domain_add" --destination="$hooks_dir/post_domain_add/01-post_domain_add_$app"
ynh_config_add --template="$data_dir/post_domain_remove/01-post_domain_remove" --destination="$hooks_dir/post_domain_remove/01-post_domain_remove_$app"
ynh_config_add --template="$data_dir/post_cert_update/01-post_cert_update" --destination="$hooks_dir/post_cert_update/01-post_cert_update_$app"
ynh_config_add --template="$data_dir/backup/01-backup" --destination="$hooks_dir/backup/01-backup_$app"
ynh_config_add --template="$data_dir/restore/01-restore" --destination="$hooks_dir/restore/01-restore_$app"
ynh_config_add --template="$data_dir/post_app_install/01-post_app_install" --destination="$hooks_dir/post_app_install/01-post_app_install_$app"
ynh_config_add --template="$data_dir/post_app_remove/01-post_app_remove" --destination="$hooks_dir/post_app_remove/01-post_app_remove_$app"
ynh_config_add --template="$data_dir/post_app_upgrade/01-post_app_upgrade" --destination="$hooks_dir/post_app_upgrade/01-post_app_upgrade_$app"
ynh_config_add --template="$data_dir/etc/profile.d/gotify_ssh_login.sh" --destination="/etc/profile.d/gotify_ssh_login_$app.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
