#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

ynh_safe_rm $data_dir

ynh_setup_source --dest_dir="$data_dir"

#=================================================
# SETUP HOOKS
#=================================================

ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/backup"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/restore"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_install"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_remove"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_app_upgrade"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_cert_update"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_domain_add"
ynh_replace --match="__GOTIFYPATH__" --replace="$gotifypath" --file="../hooks/post_domain_remove"

ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/backup"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/restore"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_install"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_remove"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_app_upgrade"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_cert_update"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_domain_add"
ynh_replace --match="__TOKEN__" --replace="$token" --file="../hooks/post_domain_remove"

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating $app's configuration files..."

ynh_safe_rm  "/etc/profile.d/gotify_ssh_login_$app.sh"

ynh_config_add --template="$data_dir/etc/profile.d/gotify_ssh_login.sh" --destination="/etc/profile.d/gotify_ssh_login_$app.sh"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
